name: Testing
run-name: testing ${{ github.repository }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: python3 -m pip install poetry
      - name: Lance les tests
        run: |
          poetry install
          poetry run pytest tests/*
