name: Publishing
run-name: publishing on pypi ${{ github.repository }}

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TAG: $(git describe --tags)
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v2
      - name: Installer les dépendances
        run: |
          pip install poetry
      - name: Execute les tests
        run: |
          poetry install
          poetry run pytest tests/
      - name: Changement du tag
        run: |
          poetry version ${{ env.TAG }}
      - name: Build and Publish
        run: |
          poetry build
          poetry publish -u $USERNAME -p $PASSWORD
